#ifndef DEFINES_H
#define DEFINES_H

#define ROM_SIZE 								0x40010

#define CHR_FONT								0x24810

#define STARTINGGOLD_OFFSET  					0x302C

#define CHARBATTLEPIC_OFFSET  					0x25010
#define CHARBATTLEPALETTE_OFFSET  				0x3EBB5
#define CHARBATTLEPALETTE_ASSIGNMENT1  			0x3204C
#define CHARBATTLEPALETTE_ASSIGNMENT2  			0x3ECB4
#define MAPMANPALETTE_OFFSET  					0x3B0
#define MAPMANGRAPHIC_OFFSET  					0x9010

#define CLASS_OFFSET  							0x3050
#define CLASS_BYTES  							16

#define STAMPEDROM_OFFSET  						0x3FFFF

#define STARTINGMP_OFFSET  						0x3C7E6
#define MAGICMIN_OFFSET  						0x3C7DE
#define MAGICMAX_OFFSET  						0x3C7E2
#define HPRANGEMIN_OFFSET  						0x2DCD8
#define HPRANGEMAX_OFFSET  						0x2DCDA
#define LOCKFIGHTERTHIEF_OFFSET  				0x2DC7D
#define LEVELUP_OFFSET  						0x2D0A4
#define EXP_OFFSET  							0x2D010
#define HITPCTINCREASE_OFFSET  					0x2DDEC

#define BATTLEDOMAIN_OFFSET  					0x2C010
#define BATTLEPROBABILITY_OFFSET  				0x3C59C

#define MAPPALETTE_OFFSET  						0x2010
#define MAPTILESET_ASSIGNMENT  					0x2CD0
#define TILESETPATTERNTABLE_OFFSET  			0xC010
#define TILESETPATTERNTABLE_ASSIGNMENT  		0x1010
#define TILESETPALETTE_ASSIGNMENT  				0x410
#define TILESET_TILEDATA  						0x810

#define OVERWORLDPALETTE_OFFSET  				0x390
#define OVERWORLDPALETTE_ASSIGNMENT  			0x310
#define OVERWORLDPATTERNTABLE_OFFSET  			0x8010
#define OVERWORLDPATTERNTABLE_ASSIGNMENT  		0x110
#define OVERWORLD_TILEDATA  					0x10
#define BATTLEBACKDROPASSIGNMENT_OFFSET  		0x3310
#define BATTLEBACKDROPPALETTE_OFFSET  			0x3210
#define MAPSPRITEPATTERNTABLE_OFFSET  			0xA210
#define MAPSPRITEPATTERNTABLE_COUNT  			0x1E

#define OVERWORLDMAP_OFFSET  					0x4010
#define OVERWORLDMAP_PTRADD  					-0x3FF0
#define OVERWORLDMAP_START  					0x4210
#define OVERWORLDMAP_END  						0x7F50
#define MAP_OFFSET  							0x10010
#define MAP_PTRADD  							0x10010
#define MAP_START  								0x10090
#define MAP_END  								0x1C010
#define MAPSPRITE_COUNT  						0x10
#define MAPSPRITE_PICASSIGNMENT  				0x2E10
#define MAPSPRITE_OFFSET  						0x3410
#define SPRITE_COUNT 	 						0xD0
#define MAPSPRITEGRAPHIC_COUNT 					0x1E

#define BASICTEXT_OFFSET 						0x2B712
#define BASICTEXT_PTRADD  						0x20010
#define ATTACKTEXT_OFFSET  						0x2B610
#define ATTACKTEXT_PTRADD  						0x20010
#define ENEMYTEXT_OFFSET  						0x2D4F0
#define ENEMYTEXT_PTRADD  						0x24010
#define BATTLEMESSAGETEXT_OFFSET  				0x2CF60
#define BATTLEMESSAGETEXT_PTRADD  				0x24010
#define DIALOGUE_OFFSET  						0x28010
#define DIALOGUE_PTRADD  						0x20010

#define BASICTEXT_START  						0x2B910
#define BASICTEXT_END  							0x2BFB3
#define ATTACKTEXT_START  						0x2B644
#define ATTACKTEXT_END  						0x2B6F5
#define ENEMYTEXT_START  						0x2D5F0
#define ENEMYTEXT_END  							0x2D957
#define DIALOGUE_START  						0x28210
#define DIALOGUE_END  							0x2B610
#define BATTLEMESSAGETEXT_START  				0x2CC50
#define BATTLEMESSAGETEXT_END  					0x2CF60

#define	ITEM_COUNT								27
#define WEAPON_COUNT 							40
#define ARMOR_COUNT 							40
#define GOLDITEM_COUNT 							68
#define MAGIC_COUNT 							64
#define CLASS_COUNT 							12

#define ATTACK_COUNT							26;
#define ENEMY_COUNT 							128;
#define BATTLEMESSAGE_COUNT 					78;
#define DIALOGUE_COUNT 							256

#define WEAPONTEXT_OFFSET 						BASICTEXT_OFFSET + (ITEM_COUNT << 1);
#define ARMORTEXT_OFFSET 						WEAPONTEXT_OFFSET + (WEAPON_COUNT << 1);
#define GOLDITEMTEXT_OFFSET 					ARMORTEXT_OFFSET + (ARMOR_COUNT << 1);
#define MAGICTEXT_OFFSET 						GOLDITEMTEXT_OFFSET + (GOLDITEM_COUNT << 1);
#define CLASSTEXT_OFFSET 						MAGICTEXT_OFFSET + (MAGIC_COUNT << 1);

#define	ITEMPRICE_OFFSET 						0x37C12

#define ARMOR_OFFSET 							0x30150
#define ARMORPERMISSIONS_OFFSET 				0x3BFB0
#define ARMORPRICE_OFFSET 						0x37C98
#define ARMOR_BYTES 							4

#define WEAPON_OFFSET 							0x30010
#define WEAPONPERMISSIONS_OFFSET 				0x3BF60
#define WEAPONPRICE_OFFSET 						0x37C48
#define WEAPON_BYTES 							8


#define WEAPONMAGICGRAPHIC_OFFSET 				0x26810
#define WEAPONMAGICGRAPHIC_COUNT 				28
#define FINGERGRAPHIC_OFFSET 					0x26F10

#define AI_COUNT 								44
#define AI_OFFSET 								0x31030
#define ENEMY_OFFSET 							0x30530
#define ENEMY_BYTES 							20

#define ATTACK_OFFSET 							0x30400
#define ATTACK_BYTES 							8

#define MAGIC_OFFSET 							0x301F0
#define MAGIC_BYTES 							8
#define MAGICPRICE_OFFSET 						0x37D70
#define MAGICPERMISSIONS_OFFSET 				0x3AD28
#define BATTLEMESSAGE_OFFSET 					0x304D0

#define SHOP_OFFSET 							0x38312
#define SHOP_PTRADD 							0x30010
#define SHOP_START 								0x3839E
#define SHOP_END 								0x38490
#define SHOP_COUNT 								70

#define BATTLE_COUNT							0x80
#define BATTLEPATTERNTABLE_COUNT				0x10

#define BATTLE_OFFSET 							0x2C410
#define BATTLE_BYTES 							0x10
#define BATTLEPALETTE_OFFSET 					0x30F30
#define BATTLEPATTERNTABLE_OFFSET 				0x1C010

#define FIENDDRAW_TABLE 						0x2D2F0
#define FIENDPALETTE_TABLE 						0x2D330
#define FIENDDRAW_SHIFT 						0x50
#define CHAOSDRAW_TABLE 						0x2D430
#define CHAOSPALETTE_TABLE 						0x2D4D8

#define ONTELEPORT_COUNT 						0x20
#define ONTELEPORT_OFFSET 						0x2C10
#define NNTELEPORT_COUNT						0x40
#define NNTELEPORT_OFFSET 						0x2D10
#define NOTELEPORT_COUNT						0x10
#define NOTELEPORT_OFFSET 						0x2C70

#define MAP_COUNT 								61
#define TREASURE_OFFSET 						0x3110
#define TREASURE_COUNT 							256
#define TILESET_COUNT 							8

//label sizes
#define TEXTLABEL_SIZE 							30
#define WEAPONMAGICGRAPHICLABEL_SIZE 		    20
#define AILABEL_SIZE							20
#define SHOPLABEL_SIZE	 						30
#define BATTLELABEL_SIZE 						30
#define BATTLEPATTERNTABLELABEL_SIZE			40
#define BACKDROPLABEL_SIZE 						10
#define TELEPORTLABEL_SIZE 						30
#define MAPLABEL_SIZE 							20
#define TCLABEL_SIZE							20
#define TILESETLABEL_SIZE 						10
#define SPRITELABEL_SIZE 						25
#define SPRITEGRAPHICLABEL_SIZE 				10



#endif /* DEFINES_H */